import React, { createContext, useContext, useState, useEffect } from 'react';

// 支持的语言类型
export type Language = 'en' | 'zh';

// 语言上下文类型
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

// 创建语言上下文
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译文本
const translations = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.back': 'Back',
    'common.home': 'Home',
    'common.login': 'Login',
    'common.register': 'Register',
    'common.logout': 'Logout',
    'common.profile': 'Profile',
    'common.settings': 'Settings',
    'common.free': 'Free',
    'common.price': 'Price',
    'common.rating': 'Rating',
    'common.reviews': 'Reviews',
    'common.categories': 'Categories',
    'common.tags': 'Tags',
    'common.creator': 'Creator',
    'common.created': 'Created',
    'common.updated': 'Updated',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.description': 'Description',
    'common.title': 'Title',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.username': 'Username',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.show': 'Show',
    'common.hide': 'Hide',
    'common.more': 'More',
    'common.less': 'Less',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.or': 'or',
    'common.and': 'and',

    // Navigation
    'nav.home': 'Home',
    'nav.discover': 'Discover',
    'nav.trending': 'Trending',
    'nav.featured': 'Featured',
    'nav.categories': 'Categories',
    'nav.search.placeholder': 'Search workflows...',
    'nav.user.menu.profile': 'Profile',
    'nav.user.menu.workflows': 'My Workflows',
    'nav.user.menu.purchases': 'Purchases',
    'nav.user.menu.creator': 'Creator Center',
    'nav.user.menu.settings': 'Settings',
    'nav.user.menu.logout': 'Logout',

    // Brand
    'brand.name': 'Workflow Hub',
    'brand.tagline': 'Discover and share high-quality workflows to boost your productivity',

    // Footer
    'footer.product': 'Product',
    'footer.support': 'Support',
    'footer.help': 'Help Center',
    'footer.contact': 'Contact Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2024 Workflow Hub. All rights reserved.',

    // Home Page
    'home.hero.title': 'Discover the Best',
    'home.hero.title.highlight': 'Workflows',
    'home.hero.subtitle': 'Explore high-quality workflows created by the community to boost your productivity',
    'home.hero.search.placeholder': 'Search workflows, categories, or tags...',
    'home.stats.workflows': 'Workflows',
    'home.stats.users': 'Users',
    'home.stats.downloads': 'Downloads',
    'home.stats.categories': 'Categories',
    'home.categories.title': 'Popular Categories',
    'home.categories.subtitle': 'Explore professional workflows in different fields',
    'home.featured.title': 'Featured Workflows',
    'home.featured.subtitle': 'Editor-recommended high-quality workflows',
    'home.popular.title': 'Popular Workflows',
    'home.popular.subtitle': 'Most popular workflows in the community',
    'home.recent.title': 'Latest Workflows',
    'home.recent.subtitle': 'Recently published new workflows',
    'home.cta.title': 'Ready to share your workflows?',
    'home.cta.subtitle': 'Join our creator community, share your creativity, and earn revenue',
    'home.cta.start': 'Start Creating',
    'home.cta.learn': 'Learn More',
    'home.viewAll': 'View All',

    // Categories
    'category.motherBaby': 'Mother & Baby',
    'category.motherBaby.desc': 'Tools and resources for parenting and baby care',
    'category.books': 'Books',
    'category.books.desc': 'Book recommendations and reading management tools',
    'category.health': 'Health & Wellness',
    'category.health.desc': 'Health management and wellness lifestyle tools',
    'category.workflows': 'workflows',

    // Search Page
    'search.title': 'Search Results',
    'search.placeholder': 'Search workflows, creators, or tags...',
    'search.filters': 'Filters',
    'search.category': 'Category',
    'search.price': 'Price',
    'search.rating': 'Rating',
    'search.sort.latest': 'Latest',
    'search.sort.popular': 'Popular',
    'search.sort.rating': 'Highest Rated',
    'search.sort.price.asc': 'Price: Low to High',
    'search.sort.price.desc': 'Price: High to Low',
    'search.price.free': 'Free',
    'search.price.1-10': '¥1-10',
    'search.price.10-50': '¥10-50',
    'search.price.50-100': '¥50-100',
    'search.price.100+': '¥100+',
    'search.rating.5': '5 stars',
    'search.rating.4': '4+ stars',
    'search.rating.3': '3+ stars',
    'search.rating.2': '2+ stars',
    'search.clearFilters': 'Clear All Filters',
    'search.noResults': 'No workflows found',
    'search.noResults.desc': 'Try adjusting your search keywords or filters',
    'search.results': 'search results',
    'search.resultsFor': 'Search results for',

    // Workflow Detail
    'workflow.details': 'Workflow Details',
    'workflow.creator': 'Creator',
    'workflow.category': 'Category',
    'workflow.price': 'Price',
    'workflow.rating': 'Rating',
    'workflow.downloads': 'Downloads',
    'workflow.views': 'Views',
    'workflow.published': 'Published',
    'workflow.updated': 'Updated',
    'workflow.security': 'Security Check: Passed',
    'workflow.buyNow': 'Buy Now',
    'workflow.downloadNow': 'Download Now',
    'workflow.addToFavorites': 'Add to Favorites',
    'workflow.share': 'Share',
    'workflow.follow': 'Follow',
    'workflow.description': 'Description',
    'workflow.instructions': 'Instructions',
    'workflow.reviews': 'Reviews',
    'workflow.related': 'Related Workflows',
    'workflow.noDescription': 'No description available',
    'workflow.noTags': 'No tags',
    'workflow.noReviews': 'No reviews yet',
    'workflow.writeReview': 'Write a Review',
    'workflow.reviewContent': 'Review Content',
    'workflow.reviewPlaceholder': 'Share your experience...',
    'workflow.submitReview': 'Submit Review',
    'workflow.helpful': 'Helpful',
    'workflow.report': 'Report',
    'workflow.featured': 'Featured',
    'workflow.notFound': 'Workflow Not Found',
    'workflow.notFound.desc': 'The workflow you are looking for does not exist or has been deleted',

    // Profile Page
    'profile.title': 'Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.favorites': 'My Favorites',
    'profile.purchases': 'Purchase History',
    'profile.transactions': 'Transaction History',
    'profile.settings': 'Account Settings',
    'profile.edit': 'Edit',
    'profile.save': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.bio': 'Bio',
    'profile.bio.placeholder': 'Tell us about yourself...',
    'profile.location': 'Location',
    'profile.location.placeholder': 'e.g., New York',
    'profile.website': 'Website',
    'profile.website.placeholder': 'https://example.com',
    'profile.joinDate': 'Member since',
    'profile.noFavorites': 'No favorites yet',
    'profile.noFavorites.desc': 'Favorite interesting workflows for easy access',
    'profile.noPurchases': 'No purchase history',
    'profile.noPurchases.desc': 'Purchased workflows will appear here',
    'profile.noTransactions': 'No transaction history',
    'profile.noTransactions.desc': 'Your transaction history will appear here',
    'profile.security': 'Account Security',
    'profile.changePassword': 'Change Password',
    'profile.changePassword.desc': 'Update your password regularly to protect your account',
    'profile.twoFactor': 'Two-Factor Authentication',
    'profile.twoFactor.desc': 'Add extra security protection to your account',
    'profile.enable': 'Enable',
    'profile.notifications': 'Notification Settings',
    'profile.emailNotifications': 'Email Notifications',
    'profile.emailNotifications.desc': 'Receive important updates and notifications',
    'profile.pushNotifications': 'Push Notifications',
    'profile.pushNotifications.desc': 'Receive browser push notifications',
    'profile.privacy': 'Privacy Settings',
    'profile.publicProfile': 'Public Profile',
    'profile.publicProfile.desc': 'Allow other users to view your profile',
    'profile.showPurchases': 'Show Purchase History',
    'profile.showPurchases.desc': 'Display purchased workflows in your profile',
    'profile.loginRequired': 'Please log in first',
    'profile.loginRequired.desc': 'You need to log in to access your profile',
    'profile.goLogin': 'Go to Login',

    // Creator Page
    'creator.title': 'Creator Center',
    'creator.subtitle': 'Manage your workflows and earnings',
    'creator.overview': 'Overview',
    'creator.workflows': 'My Works',
    'creator.analytics': 'Analytics',
    'creator.earnings': 'Earnings',
    'creator.settings': 'Settings',
    'creator.totalEarnings': 'Total Earnings',
    'creator.monthlyEarnings': 'Monthly Earnings',
    'creator.workflowCount': 'Works Count',
    'creator.totalDownloads': 'Total Downloads',
    'creator.quickActions': 'Quick Actions',
    'creator.uploadNew': 'Upload New Workflow',
    'creator.viewAnalytics': 'View Analytics',
    'creator.withdraw': 'Withdraw Earnings',
    'creator.latestWorks': 'Latest Works',
    'creator.noWorks': 'No works yet',
    'creator.noWorks.desc': 'Upload your first workflow to start earning',
    'creator.uploadWorkflow': 'Upload Workflow',
    'creator.status.pending': 'Pending',
    'creator.status.approved': 'Approved',
    'creator.status.rejected': 'Rejected',
    'creator.status.offline': 'Offline',
    'creator.totalViews': 'Total Views',
    'creator.conversionRate': 'Conversion Rate',
    'creator.averageRating': 'Average Rating',
    'creator.downloadTrend': 'Download Trend',
    'creator.earningsTrend': 'Earnings Trend',
    'creator.chartPlaceholder': 'Chart feature in development...',
    'creator.withdrawableBalance': 'Withdrawable Balance',
    'creator.totalWithdrawn': 'Total Withdrawn',
    'creator.applyWithdraw': 'Apply for Withdrawal',
    'creator.withdrawNote': 'Minimum withdrawal amount is ¥100. Withdrawal requests will be processed within 3-5 business days.',
    'creator.withdrawAmount': 'Withdrawal Amount',
    'creator.earningsHistory': 'Earnings History',
    'creator.noEarnings': 'No earnings history',
    'creator.creatorInfo': 'Creator Information',
    'creator.creatorBio': 'Creator Bio',
    'creator.creatorBio.placeholder': 'Introduce your professional background and creative philosophy...',
    'creator.expertise': 'Expertise',
    'creator.expertise.placeholder': 'e.g., Automation, Data Analysis, Design',
    'creator.earningsSettings': 'Earnings Settings',
    'creator.autoWithdraw': 'Auto Withdrawal',
    'creator.autoWithdraw.desc': 'Automatically apply for withdrawal when balance reaches specified amount',
    'creator.autoWithdrawAmount': 'Auto Withdrawal Amount',
    'creator.permissionRequired': 'Creator Permission Required',
    'creator.permissionRequired.desc': 'You need to become a creator to access this page',
    'creator.becomeCreator': 'Become a Creator',

    // Become Creator Page
    'becomeCreator.title': 'Apply to Become a Creator',
    'becomeCreator.subtitle': 'Join our creator community, share your workflows and earn revenue',
    'becomeCreator.loginRequired': 'Login Required',
    'becomeCreator.loginRequired.desc': 'Please log in to your account first to apply to become a creator',
    'becomeCreator.loginButton': 'Login Now',
    'becomeCreator.alreadyCreator': 'You are already a creator',
    'becomeCreator.alreadyCreator.desc': 'You already have creator permissions and can start uploading and managing your workflows',
    'becomeCreator.goToCreatorCenter': 'Go to Creator Center',
    'becomeCreator.applicationSubmitted': 'Application Submitted',
    'becomeCreator.applicationSubmitted.desc': 'Your creator application has been successfully submitted. We will review your application within 3-5 business days. The review result will be notified to you via email.',
    'becomeCreator.backToHome': 'Back to Home',
    'becomeCreator.viewProfile': 'View Profile',
    'becomeCreator.benefits.upload.title': 'Upload Works',
    'becomeCreator.benefits.upload.desc': 'Upload your workflow templates to help other users improve work efficiency',
    'becomeCreator.benefits.earn.title': 'Earn Revenue',
    'becomeCreator.benefits.earn.desc': 'Earn revenue by selling workflows, with commission for each download',
    'becomeCreator.benefits.reputation.title': 'Build Reputation',
    'becomeCreator.benefits.reputation.desc': 'Get user reviews and followers, build your professional reputation',
    'becomeCreator.form.title': 'Creator Application Form',
    'becomeCreator.form.username': 'Username',
    'becomeCreator.form.username.placeholder': 'Enter your username',
    'becomeCreator.form.email': 'Email Address',
    'becomeCreator.form.email.placeholder': 'Enter your email address',
    'becomeCreator.form.country': 'Country/Region',
    'becomeCreator.form.country.placeholder': 'Enter your country or region',
    'becomeCreator.form.linkedin': 'LinkedIn Profile',
    'becomeCreator.form.linkedin.placeholder': 'https://linkedin.com/in/yourprofile (optional)',
    'becomeCreator.form.skills': 'Professional Skills',
    'becomeCreator.form.skills.placeholder': 'List your key skills relevant to workflow automation, design, development, etc...',
    'becomeCreator.form.experience': 'Relevant Experience',
    'becomeCreator.form.experience.placeholder': 'Describe your experience in automation, workflow design, or related fields...',
    'becomeCreator.form.portfolio': 'Portfolio/Website',
    'becomeCreator.form.portfolio.placeholder': 'Link to your portfolio or personal website (optional)',
    'becomeCreator.form.reason': 'Why do you want to become a creator?',
    'becomeCreator.form.reason.placeholder': 'Tell us why you want to become a creator and what type of workflows you plan to share...',
    'becomeCreator.form.back': 'Back',
    'becomeCreator.form.submit': 'Submit Application',
    'becomeCreator.form.submitting': 'Submitting...',
    'becomeCreator.form.required': '*',
    'becomeCreator.notice.title': 'Application Notice',
    'becomeCreator.notice.item1': 'Please ensure the information provided is true and valid, false information will result in application rejection',
    'becomeCreator.notice.item2': 'Review period is 3-5 business days, review results will be notified via email',
    'becomeCreator.notice.item3': 'After becoming a creator, you need to comply with the platform\'s creator agreement and regulations',
    'becomeCreator.notice.item4': 'The platform will conduct quality review of your uploaded workflows',

    // Login Page
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to your account to continue using Workflow Hub',
    'login.email': 'Email Address',
    'login.email.placeholder': 'Enter your email address',
    'login.password': 'Password',
    'login.password.placeholder': 'Enter your password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.loginButton': 'Sign In',
    'login.loggingIn': 'Signing in...',
    'login.socialLogin': 'Sign in with WeChat',
    'login.socialLogin.qq': 'Sign in with QQ',
    'login.noAccount': "Don't have an account?",
    'login.signUp': 'Sign up now',
    'login.terms': 'By signing in, you agree to our',
    'login.termsLink': 'Terms of Service',
    'login.privacyLink': 'Privacy Policy',
    'login.error.email': 'Please enter a valid email address',
    'login.error.password': 'Password must be at least 6 characters',
    'login.error.required': 'This field is required',

    // Register Page
    'register.title': 'Create Account',
    'register.subtitle': 'Join Workflow Hub and start your productive journey',
    'register.step1': 'Basic Information',
    'register.step1.desc': 'Please fill in your basic registration information',
    'register.step2': 'Choose Your Role',
    'register.step2.desc': 'Different roles have different permissions',
    'register.username': 'Username',
    'register.username.placeholder': 'Enter your username',
    'register.email': 'Email Address',
    'register.email.placeholder': 'Enter your email address',
    'register.password': 'Password',
    'register.password.placeholder': 'Enter your password',
    'register.confirmPassword': 'Confirm Password',
    'register.confirmPassword.placeholder': 'Enter your password again',
    'register.role.user': 'Regular User',
    'register.role.user.desc': 'Browse and purchase workflows',
    'register.role.creator': 'Creator',
    'register.role.creator.desc': 'Upload and sell workflows',
    'register.role.advertiser': 'Advertiser',
    'register.role.advertiser.desc': 'Place ads and promotions',
    'register.agreeTerms': 'I have read and agree to the',
    'register.nextStep': 'Next Step',
    'register.prevStep': 'Previous Step',
    'register.complete': 'Complete Registration',
    'register.registering': 'Registering...',
    'register.hasAccount': 'Already have an account?',
    'register.signIn': 'Sign in now',
    'register.passwordStrength.weak': 'Very Weak',
    'register.passwordStrength.fair': 'Weak',
    'register.passwordStrength.good': 'Fair',
    'register.passwordStrength.strong': 'Strong',
    'register.passwordStrength.excellent': 'Very Strong',
    'register.error.username': 'Username must be at least 3 characters and contain only letters, numbers, underscores',
    'register.error.email': 'Please enter a valid email address',
    'register.error.password': 'Password must contain uppercase, lowercase letters and numbers',
    'register.error.confirmPassword': 'Passwords do not match',
    'register.error.terms': 'Please agree to the Terms of Service and Privacy Policy',

    // 404 Page
    '404.title': '404',
    '404.message': 'Page Not Found',
    '404.backHome': 'Back to Home',

    // Error Messages
    'error.network': 'Network error, please try again',
    'error.server': 'Server error, please try again later',
    'error.unauthorized': 'Unauthorized access',
    'error.forbidden': 'Access forbidden',
    'error.notFound': 'Resource not found',
    'error.validation': 'Validation error',
    'error.unknown': 'Unknown error occurred',

    // Success Messages
    'success.saved': 'Saved successfully',
    'success.updated': 'Updated successfully',
    'success.deleted': 'Deleted successfully',
    'success.uploaded': 'Uploaded successfully',
    'success.downloaded': 'Downloaded successfully',
    'success.login': 'Login successful',
    'success.register': 'Registration successful',
    'success.logout': 'Logout successful',

    // AI Apps Page
    'aiApps.title': 'Explore AI Applications',
    'aiApps.subtitle': 'Discover and use various intelligent AI applications to improve work efficiency',
    'aiApps.featured': 'Featured AI Apps',
    'aiApps.freeToUse': 'Free to Use',
    'aiApps.becomeCreator': 'Become a Creator',
    'aiApps.loading': 'Loading...',
    'aiApps.noApps': 'No AI Applications',
    'aiApps.noAppsDesc': 'No AI applications available at the moment',
    'aiApps.featured.badge': 'Featured',
    'aiApps.hoursAgo': '2 hours ago',
    'aiApps.defaultDesc': 'Play a game similar to "Deep Sea Landing" element synthesis. The initial elements are 🔥 Fire, 💧 Water, 🌪️ Wind, 🌍 Earth, you can synthesize more elements through these basic elements...',
    'aiApps.pagination.prev': 'Previous',
    'aiApps.pagination.next': 'Next',

    // Workflows Page
    'workflows.unmute': 'Click to enable sound',
    'workflows.mute': 'Click to mute',
    'workflows.featured': 'Featured',
    'workflows.free': 'Free',
    'workflows.error.fetchFailed': 'Failed to load workflows, please try again later',
    'workflows.creator.apply': 'Apply to Become Creator',
    'workflows.creator.description': 'Publish workflows or AI applications to earn revenue',
    'workflows.creator.benefits.revenue': 'Earn revenue share',
    'workflows.creator.benefits.showcase': 'Showcase your work',
    'workflows.creator.applyNow': 'Apply Now',
    'workflows.sort.trending': 'Trending',
    'workflows.sort.downloads': 'Most Downloads',
    'workflows.sort.rating': 'Highest Rated',
    'workflows.sort.latest': 'Latest',
    'workflows.loading': 'Loading workflows...',
    'workflows.error.title': 'Load Failed',
    'workflows.retry': 'Retry',
    'workflows.empty.title': 'No Workflows',
    'workflows.empty.description': 'Try adjusting search criteria or category filters',
    'workflows.pagination.previous': 'Previous',
    'workflows.pagination.next': 'Next',

    // Navigation
    'nav.notifications': 'Notifications',
    'nav.lightMode': 'Light Mode',
    'nav.darkMode': 'Dark Mode',
    'nav.limitedOffer': '🎉 Limited Time: Workflow Templates 20% Off!',
    'nav.membership': 'Membership',
    'nav.upgrade': 'Upgrade',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.aiApps': 'AI Apps',
    'nav.workflows': 'Workflows',
    'nav.coze': 'Coze Workflows',
    'nav.taskHall': 'Task Hall',
    'nav.creator': 'Creator Center',
    'nav.profile': 'Profile',
    'nav.my': 'My',
    'nav.logout': 'Logout',
    'nav.myWallet': 'My Wallet',
    'nav.wechatMiniProgram': 'WeChat Mini Program',
    'nav.miniProgramName': 'Iron Man Jarvis',
    'nav.scanToExperience': 'Scan to experience mini program',
    'nav.inviteFriends': 'Invite friends to earn WH coins',
    'nav.inviteReward': 'Get 100 coins for each invitation',

    // Login Prompts
    'auth.loginRequired': 'Please login first',
    'auth.loginToAccess': 'You need to login to access this page',
    'auth.loginToAccessProfile': 'You need to login to access personal center',
    'auth.loginToViewWallet': 'Login to view your wallet information',
    'auth.loginToUseApp': 'Please login before using AI applications',
    'auth.loginNow': 'Login Now',
    'auth.goLogin': 'Go to Login',

    // Wallet Page
    'wallet.title': 'My Wallet',
    'wallet.subtitle': 'Manage your membership status and account balance',
    'wallet.loadFailed': 'Load Failed',
    'wallet.reload': 'Reload',
    'wallet.membershipStatus': 'Membership Status',
    'wallet.startTime': 'Start Time',
    'wallet.endTime': 'End Time',
    'wallet.remainingDays': 'Remaining Days',
    'wallet.expired': 'Expired',
    'wallet.days': 'days',
    'wallet.autoRenew': 'Auto Renew',
    'wallet.enabled': 'Enabled',
    'wallet.disabled': 'Disabled',
    'wallet.notSet': 'Not Set',
    'wallet.membershipBenefits': 'Membership Benefits',
    'wallet.activateMembership': 'Activate Membership',
    'wallet.upgradeMembership': 'Upgrade Membership',
    'wallet.manageRenewal': 'Manage Renewal',
    'wallet.whCoinsBalance': 'WH Coins Balance',
    'wallet.whCoinsDescription': 'Can be used to purchase memberships and other services',
    'wallet.rechargeCoins': 'Recharge WH Coins',
    'wallet.transactionHistory': 'Transaction History',
    'wallet.quickActions': 'Quick Actions',
    'wallet.inviteFriends': 'Invite Friends',
    'wallet.accountSettings': 'Account Settings',
    'wallet.membershipExpired': 'Membership Expired',
    'wallet.membershipExpiredDesc': 'Your membership has expired, please renew to continue enjoying membership benefits',
    'wallet.renewNow': 'Renew Now',
    'wallet.expiringSoon': 'Expiring Soon',
    'wallet.expiringSoonDesc': 'Your membership will expire in {days} days, please renew in time',

    // Tasks
    'tasks.title': 'Task Hall',
    'tasks.subtitle': 'Participate in tasks and earn rewards',
    'tasks.search.placeholder': 'Search task title or description...',
    'tasks.category.all': 'All Categories',
    'tasks.category.design': 'Design',
    'tasks.category.writing': 'Writing',
    'tasks.category.programming': 'Programming',
    'tasks.category.marketing': 'Marketing',
    'tasks.category.research': 'Research',
    'tasks.status.expired': 'Expired',
    'tasks.status.expiringSoon': 'Expiring Soon',
    'tasks.status.full': 'Full',
    'tasks.status.active': 'Active',
    'tasks.reward': 'Reward',
    'tasks.participants': 'Participants',
    'tasks.deadline': 'Deadline',
    'tasks.creator': 'Creator',
    'tasks.viewDetails': 'View Details',
    'tasks.noTasks': 'No tasks available',
    'tasks.loading': 'Loading...',
    'tasks.detail.title': 'Task Details',
    'tasks.detail.description': 'Description',
    'tasks.detail.requirements': 'Requirements',
    'tasks.detail.submissionFormat': 'Submission Format',
    'tasks.detail.participate': 'Participate',
    'tasks.detail.viewMySubmission': 'View My Submission',
    'tasks.detail.loginRequired': 'Login Required',
    'tasks.detail.loginToParticipate': 'Please login to participate in tasks',
    'tasks.detail.cannotParticipate': 'Cannot Participate',
    'tasks.detail.taskExpired': 'Task has expired',
    'tasks.detail.participantsFull': 'Participants limit reached',
    'tasks.detail.temporarilyUnavailable': 'Temporarily unavailable',
    'tasks.submissions.title': 'My Submissions',
    'tasks.submissions.stats.total': 'Total Participated',
    'tasks.submissions.stats.pending': 'Under Review',
    'tasks.submissions.stats.approved': 'Approved',
    'tasks.submissions.stats.rejected': 'Rejected',
    'tasks.submissions.stats.totalEarnings': 'Total Earnings',
    'tasks.submissions.filter.all': 'All Status',
    'tasks.submissions.filter.pending': 'Under Review',
    'tasks.submissions.filter.approved': 'Approved',
    'tasks.submissions.filter.rejected': 'Rejected',
    'tasks.submissions.status.pending': 'Under Review',
    'tasks.submissions.status.approved': 'Approved',
    'tasks.submissions.status.rejected': 'Rejected',
    'tasks.submissions.submittedAt': 'Submitted At',
    'tasks.submissions.reviewedAt': 'Reviewed At',
    'tasks.submissions.actions.view': 'View',
    'tasks.submissions.actions.edit': 'Edit',
    'tasks.submissions.actions.withdraw': 'Withdraw',
    'tasks.submissions.noSubmissions': 'No submissions yet',
    'tasks.submissions.loading': 'Loading...',
    'tasks.submit.title': 'Submit Task',
    'tasks.submit.content': 'Submission Content',
    'tasks.submit.contentPlaceholder': 'Please enter your submission content...',
    'tasks.submit.attachments': 'Attachments',
    'tasks.submit.submit': 'Submit',
    'tasks.submit.submitting': 'Submitting...',
    'tasks.submit.success': 'Submitted successfully',
    'tasks.submit.failed': 'Submission failed'
  },
  zh: {
    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.save': '保存',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.view': '查看',
    'common.download': '下载',
    'common.upload': '上传',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.sort': '排序',
    'common.next': '下一步',
    'common.previous': '上一步',
    'common.back': '返回',
    'common.home': '首页',
    'common.login': '登录',
    'common.register': '注册',
    'common.logout': '退出登录',
    'common.profile': '个人资料',
    'common.settings': '设置',
    'common.free': '免费',
    'common.price': '价格',
    'common.rating': '评分',
    'common.reviews': '评价',
    'common.categories': '分类',
    'common.tags': '标签',
    'common.creator': '创作者',
    'common.created': '创建时间',
    'common.updated': '更新时间',
    'common.status': '状态',
    'common.actions': '操作',
    'common.description': '描述',
    'common.title': '标题',
    'common.email': '邮箱',
    'common.password': '密码',
    'common.username': '用户名',
    'common.submit': '提交',
    'common.close': '关闭',
    'common.open': '打开',
    'common.show': '显示',
    'common.hide': '隐藏',
    'common.more': '更多',
    'common.less': '收起',
    'common.all': '全部',
    'common.none': '无',
    'common.yes': '是',
    'common.no': '否',
    'common.or': '或',
    'common.and': '和',

    // Navigation
    'nav.home': '首页',
    'nav.discover': '发现',
    'nav.trending': '热门',
    'nav.featured': '精选',
    'nav.categories': '分类',
    'nav.search.placeholder': '搜索工作流...',
    'nav.user.menu.profile': '个人资料',
    'nav.user.menu.workflows': '我的工作流',
    'nav.user.menu.purchases': '购买记录',
    'nav.user.menu.creator': '创作者中心',
    'nav.user.menu.settings': '设置',
    'nav.user.menu.logout': '退出登录',

    // Brand
    'brand.name': '工作流分享平台',
    'brand.tagline': '发现和分享高质量的工作流，提升您的工作效率',

    // Footer
    'footer.product': '产品',
    'footer.support': '支持',
    'footer.help': '帮助中心',
    'footer.contact': '联系我们',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.copyright': '© 2024 工作流分享平台. 保留所有权利.',

    // Home Page
    'home.hero.title': '发现最佳',
    'home.hero.title.highlight': '工作流',
    'home.hero.subtitle': '探索由社区创建的高质量工作流，提升您的工作效率',
    'home.hero.search.placeholder': '搜索工作流、分类或标签...',
    'home.stats.workflows': '工作流',
    'home.stats.users': '用户',
    'home.stats.downloads': '下载量',
    'home.stats.categories': '分类',
    'home.categories.title': '热门分类',
    'home.categories.subtitle': '探索不同领域的专业工作流',
    'home.featured.title': '精选工作流',
    'home.featured.subtitle': '编辑推荐的高质量工作流',
    'home.popular.title': '热门工作流',
    'home.popular.subtitle': '社区最受欢迎的工作流',
    'home.recent.title': '最新工作流',
    'home.recent.subtitle': '刚刚发布的新工作流',
    'home.cta.title': '准备好分享您的工作流了吗？',
    'home.cta.subtitle': '加入我们的创作者社区，分享您的创意，获得收益',
    'home.cta.start': '开始创作',
    'home.cta.learn': '了解更多',
    'home.viewAll': '查看全部',

    // Categories
    'category.motherBaby': '母婴类',
    'category.motherBaby.desc': '母婴护理和育儿相关工具',
    'category.books': '书籍类',
    'category.books.desc': '图书推荐和阅读管理工具',
    'category.health': '养生类',
    'category.health.desc': '健康管理和养生生活方式工具',
    'category.workflows': '个工作流',

    // Search Page
    'search.title': '搜索结果',
    'search.placeholder': '搜索工作流、创作者或标签...',
    'search.filters': '筛选条件',
    'search.category': '分类',
    'search.price': '价格',
    'search.rating': '评分',
    'search.sort.latest': '最新发布',
    'search.sort.popular': '热门下载',
    'search.sort.rating': '评分最高',
    'search.sort.price.asc': '价格从低到高',
    'search.sort.price.desc': '价格从高到低',
    'search.price.free': '免费',
    'search.price.1-10': '¥1-10',
    'search.price.10-50': '¥10-50',
    'search.price.50-100': '¥50-100',
    'search.price.100+': '¥100以上',
    'search.rating.5': '5星',
    'search.rating.4': '4星以上',
    'search.rating.3': '3星以上',
    'search.rating.2': '2星以上',
    'search.clearFilters': '清除所有筛选',
    'search.noResults': '没有找到相关工作流',
    'search.noResults.desc': '尝试调整搜索关键词或筛选条件',
    'search.results': '个搜索结果',
    'search.resultsFor': '的搜索结果',

    // Become Creator Page
    'becomeCreator.title': '申请成为创作者',
    'becomeCreator.subtitle': '加入我们的创作者社区，分享您的工作流并获得收益',
    'becomeCreator.loginRequired': '需要登录',
    'becomeCreator.loginRequired.desc': '请先登录您的账户才能申请成为创作者',
    'becomeCreator.loginButton': '立即登录',
    'becomeCreator.alreadyCreator': '您已经是创作者',
    'becomeCreator.alreadyCreator.desc': '您已经拥有创作者权限，可以开始上传和管理您的工作流',
    'becomeCreator.goToCreatorCenter': '前往创作者中心',
    'becomeCreator.applicationSubmitted': '申请已提交',
    'becomeCreator.applicationSubmitted.desc': '您的创作者申请已成功提交，我们将在3-5个工作日内审核您的申请。审核结果将通过邮件通知您。',
    'becomeCreator.backToHome': '返回首页',
    'becomeCreator.viewProfile': '查看个人资料',
    'becomeCreator.benefits.upload.title': '上传作品',
    'becomeCreator.benefits.upload.desc': '上传您的工作流模板，帮助其他用户提高工作效率',
    'becomeCreator.benefits.earn.title': '获得收益',
    'becomeCreator.benefits.earn.desc': '通过销售工作流获得收益，每次下载都有分成',
    'becomeCreator.benefits.reputation.title': '建立声誉',
    'becomeCreator.benefits.reputation.desc': '获得用户评价和关注，建立您的专业声誉',
    'becomeCreator.form.title': '创作者申请表单',
    'becomeCreator.form.username': '用户名',
    'becomeCreator.form.username.placeholder': '请输入您的用户名',
    'becomeCreator.form.email': '邮箱地址',
    'becomeCreator.form.email.placeholder': '请输入您的邮箱地址',
    'becomeCreator.form.country': '国家/地区',
    'becomeCreator.form.country.placeholder': '请输入您的国家或地区',
    'becomeCreator.form.linkedin': 'LinkedIn档案',
    'becomeCreator.form.linkedin.placeholder': 'https://linkedin.com/in/yourprofile (可选)',
    'becomeCreator.form.skills': '专业技能',
    'becomeCreator.form.skills.placeholder': '请列出您在工作流自动化、设计、开发等方面的核心技能...',
    'becomeCreator.form.experience': '相关经验',
    'becomeCreator.form.experience.placeholder': '请描述您在自动化、工作流设计或相关领域的经验...',
    'becomeCreator.form.portfolio': '作品集/网站',
    'becomeCreator.form.portfolio.placeholder': '您的作品集或个人网站链接 (可选)',
    'becomeCreator.form.reason': '为什么想成为创作者？',
    'becomeCreator.form.reason.placeholder': '请告诉我们您想成为创作者的原因以及您计划分享什么类型的工作流...',
    'becomeCreator.form.back': '返回',
    'becomeCreator.form.submit': '提交申请',
    'becomeCreator.form.submitting': '提交中...',
    'becomeCreator.form.required': '*',
    'becomeCreator.notice.title': '申请须知',
    'becomeCreator.notice.item1': '请确保提供的信息真实有效，虚假信息将导致申请被拒绝',
    'becomeCreator.notice.item2': '审核周期为3-5个工作日，审核结果将通过邮件通知',
    'becomeCreator.notice.item3': '成为创作者后，您需要遵守平台的创作者协议和规范',
    'becomeCreator.notice.item4': '平台将对您上传的工作流进行质量审核',

    // AI Apps Page
    'aiApps.title': '探索AI应用世界',
    'aiApps.subtitle': '发现和使用各种智能AI应用，提升工作效率',
    'aiApps.featured': '精选AI应用',
    'aiApps.freeToUse': '免费使用',
    'aiApps.becomeCreator': '成为创作者',
    'aiApps.loading': '加载中...',
    'aiApps.noApps': '暂无AI应用',
    'aiApps.noAppsDesc': '暂时没有可用的AI应用',
    'aiApps.featured.badge': '精选',
    'aiApps.hoursAgo': '2小时前',
    'aiApps.defaultDesc': '通过这个方式玩一类似「深海上岸」的元素合成游戏。初始元素是 🔥 火、💧 水、🌪️ 风、🌍 土，你可以通过这些基础元素合成更多的元素...',
    'aiApps.pagination.prev': '上一页',
    'aiApps.pagination.next': '下一页',

    // Workflows Page
    'workflows.unmute': '点击启用声音',
    'workflows.mute': '点击静音',
    'workflows.featured': '精选',
    'workflows.free': '免费',
    'workflows.error.fetchFailed': '获取工作流失败，请稍后重试',
    'workflows.creator.apply': '申请成为创作者',
    'workflows.creator.description': '发布工作流或AI应用获得收益',
    'workflows.creator.benefits.revenue': '获得收益分成',
    'workflows.creator.benefits.showcase': '展示您的作品',
    'workflows.creator.applyNow': '立即申请',
    'workflows.sort.trending': '热门推荐',
    'workflows.sort.downloads': '下载最多',
    'workflows.sort.rating': '评分最高',
    'workflows.sort.latest': '最新发布',
    'workflows.loading': '正在加载工作流...',
    'workflows.error.title': '加载失败',
    'workflows.retry': '重试',
    'workflows.empty.title': '暂无工作流',
    'workflows.empty.description': '尝试调整搜索条件或分类筛选',
    'workflows.pagination.previous': '上一页',
    'workflows.pagination.next': '下一页',

    // Navigation
    'nav.notifications': '消息通知',
    'nav.lightMode': '浅色模式',
    'nav.darkMode': '深色模式',
    'nav.limitedOffer': '🎉 限时优惠：工作流模板8折起！',
    'nav.membership': '会员',
    'nav.upgrade': '升级',
    'nav.login': '登录',
    'nav.register': '注册',
    'nav.aiApps': 'AI应用',
    'nav.workflows': '工作流',
    'nav.coze': '扣子工作流',
    'nav.taskHall': '任务大厅',
    'nav.creator': '创作者中心',
    'nav.profile': '个人中心',
    'nav.my': '我的',
    'nav.logout': '退出登录',
    'nav.myWallet': '我的钱包',
    'nav.wechatMiniProgram': '微信小程序',
    'nav.miniProgramName': 'Iron Man贾维斯',
    'nav.scanToExperience': '扫码体验小程序',
    'nav.inviteFriends': '邀请好友赚WH币',
    'nav.inviteReward': '每邀请1人获得100币',

    // Login Prompts
    'auth.loginRequired': '请先登录',
    'auth.loginToAccess': '您需要登录才能访问此页面',
    'auth.loginToAccessProfile': '您需要登录才能访问个人中心',
    'auth.loginToViewWallet': '登录后查看您的钱包信息',
    'auth.loginToUseApp': '使用AI应用前请先登录',
    'auth.loginNow': '立即登录',
    'auth.goLogin': '去登录',

    // Wallet Page
    'wallet.title': '我的钱包',
    'wallet.subtitle': '管理您的会员状态和账户余额',
    'wallet.loadFailed': '加载失败',
    'wallet.reload': '重新加载',
    'wallet.membershipStatus': '会员状态',
    'wallet.startTime': '开始时间',
    'wallet.endTime': '到期时间',
    'wallet.remainingDays': '剩余天数',
    'wallet.expired': '已过期',
    'wallet.days': '天',
    'wallet.autoRenew': '自动续费',
    'wallet.enabled': '已开启',
    'wallet.disabled': '未开启',
    'wallet.notSet': '未设置',
    'wallet.membershipBenefits': '会员特权',
    'wallet.activateMembership': '立即开通会员',
    'wallet.upgradeMembership': '升级会员',
    'wallet.manageRenewal': '管理续费',
    'wallet.whCoinsBalance': 'WH币余额',
    'wallet.whCoinsDescription': '可用于购买会员和其他服务',
    'wallet.rechargeCoins': '充值WH币',
    'wallet.transactionHistory': '交易记录',
    'wallet.quickActions': '快速操作',
    'wallet.inviteFriends': '邀请好友',
    'wallet.accountSettings': '账户设置',
    'wallet.membershipExpired': '会员已过期',
    'wallet.membershipExpiredDesc': '您的会员已过期，请及时续费以继续享受会员权益',
    'wallet.renewNow': '立即续费',
    'wallet.expiringSoon': '即将过期',
    'wallet.expiringSoonDesc': '您的会员将在 {days} 天后过期，建议及时续费',

    // Tasks
    'tasks.title': '任务大厅',
    'tasks.subtitle': '参与任务，赚取奖励',
    'tasks.search.placeholder': '搜索任务标题或描述...',
    'tasks.category.all': '全部分类',
    'tasks.category.design': '设计',
    'tasks.category.writing': '写作',
    'tasks.category.programming': '编程',
    'tasks.category.marketing': '营销',
    'tasks.category.research': '调研',
    'tasks.status.expired': '已截止',
    'tasks.status.expiringSoon': '即将截止',
    'tasks.status.full': '已满员',
    'tasks.status.active': '进行中',
    'tasks.reward': '奖励',
    'tasks.participants': '参与人数',
    'tasks.deadline': '截止时间',
    'tasks.creator': '发布者',
    'tasks.viewDetails': '查看详情',
    'tasks.noTasks': '暂无任务',
    'tasks.loading': '加载中...',
    'tasks.detail.title': '任务详情',
    'tasks.detail.description': '任务描述',
    'tasks.detail.requirements': '任务要求',
    'tasks.detail.submissionFormat': '提交格式',
    'tasks.detail.participate': '参与任务',
    'tasks.detail.viewMySubmission': '查看我的提交',
    'tasks.detail.loginRequired': '需要登录',
    'tasks.detail.loginToParticipate': '请登录后参与任务',
    'tasks.detail.cannotParticipate': '无法参与',
    'tasks.detail.taskExpired': '任务已截止',
    'tasks.detail.participantsFull': '参与人数已满',
    'tasks.detail.temporarilyUnavailable': '暂时无法参与',
    'tasks.submissions.title': '我的提交',
    'tasks.submissions.stats.total': '总参与数',
    'tasks.submissions.stats.pending': '审核中',
    'tasks.submissions.stats.approved': '已通过',
    'tasks.submissions.stats.rejected': '已拒绝',
    'tasks.submissions.stats.totalEarnings': '总收益',
    'tasks.submissions.filter.all': '全部状态',
    'tasks.submissions.filter.pending': '审核中',
    'tasks.submissions.filter.approved': '已通过',
    'tasks.submissions.filter.rejected': '已拒绝',
    'tasks.submissions.status.pending': '审核中',
    'tasks.submissions.status.approved': '已通过',
    'tasks.submissions.status.rejected': '已拒绝',
    'tasks.submissions.submittedAt': '提交时间',
    'tasks.submissions.reviewedAt': '审核时间',
    'tasks.submissions.actions.view': '查看',
    'tasks.submissions.actions.edit': '编辑',
    'tasks.submissions.actions.withdraw': '撤回',
    'tasks.submissions.noSubmissions': '暂无提交记录',
    'tasks.submissions.loading': '加载中...',
    'tasks.submit.title': '提交任务',
    'tasks.submit.content': '提交内容',
    'tasks.submit.contentPlaceholder': '请输入您的提交内容...',
    'tasks.submit.attachments': '附件',
    'tasks.submit.submit': '提交',
    'tasks.submit.submitting': '提交中...',
    'tasks.submit.success': '提交成功',
    'tasks.submit.failed': '提交失败'
  }
};

// 语言提供者组件
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // 从localStorage获取保存的语言设置，默认为英文
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  // 保存语言设置到localStorage
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // 翻译函数
  const t = (key: string, params?: Record<string, string | number>): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]] || key;
    
    // 如果有参数，进行替换
    if (params && typeof translation === 'string') {
      return Object.entries(params).reduce((str, [paramKey, paramValue]) => {
        return str.replace(new RegExp(`{{${paramKey}}}`, 'g'), String(paramValue));
      }, translation);
    }
    
    return translation;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// 使用语言上下文的Hook
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageProvider;